---
title: "MakeEMLCTD"
author: "Abby Lewis"
date: "12/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
# Install and load devtools
#install.packages("devtools")
#library(devtools)

# Install and load EMLassemblyline
#install_github("EDIorg/EMLassemblyline")
library(EMLassemblyline)


#Install the required googlesheets4 package
#install.packages('googlesheets4')
#Load the library 
library(googlesheets4)
sites <- read_sheet('https://docs.google.com/spreadsheets/d/1TlQRdjmi_lzwFfQ6Ovv1CAozmCEkHumDmbg_L4A2e-8/edit#gid=124442383')
data <- read_csv("CTD_2013_2023.csv") #This is the line you need to modify!
trim_sites = function(data,sites){
  data_res_site=data%>% #Create a Reservoir/Site combo column
    mutate(res_site = trimws(paste0(Reservoir,Site)))
  sites_merged = sites%>% #Filter to Sites that are in the dataframe
    mutate(res_site = trimws(paste0(Reservoir,Site)))%>%
    filter(res_site%in%data_res_site$res_site)%>%
    select(-res_site)
}
sites_trimmed = trim_sites(data,sites) 
write.csv(sites_trimmed,"site_descriptions.csv", row.names=F)# Write to file


# Make the EML for EDI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_eml(path = getwd(),
         dataset.title = "Time series of high-frequency profiles of depth, temperature, dissolved oxygen, conductivity, specific conductivity, chlorophyll a, turbidity, pH, oxidation-reduction potential, photosynthetic active radiation, cDOM, phycocyanin, phycoerythrin, and descent rate for Beaverdam Reservoir, Carvins Cove Reservoir, Falling Creek Reservoir, Gatewood Reservoir, and Spring Hollow Reservoir in Southwestern Virginia, USA 2013-2023",
         data.table = c("CTD_2013_2023.csv",
                        "site_descriptions.csv"),
         data.table.name = c("CTD dataset 2013-2023",
                             "Descriptions of sample sites"),
         data.table.description = c("Reservoir CTD dataset",
                                    "Sample site descriptions"),
         other.entity = c('CTD_QAQC_2018_2023.R', 
                          "helper_scripts.zip"),
         other.entity.name = c('QAQC script', 
                               "Helper scripts"),
         other.entity.description = c('High-level QAQC script used to process data from 2018-2023 - 
                                      references scripts in helper_scripts.zip', 
                                      "Scripts used to compile casts and apply QAQC, 
                                      as referenced by CTD_QAQC_2018_2023.R"),
         temporal.coverage = c("2013-03-07", "2023-12-04"),
         maintenance.description = "ongoing",
         user.domain = "EDI",
         user.id = "ccarey",
         package.id = "edi.1113.1") #staging 2023
```

